[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:loihi_server]
command=python server/loihi_server.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/loihi_server.err.log
stdout_logfile=/var/log/loihi_server.out.log
environment=PORT="8000"

[program:discovery_server]
command=python server/run_discovery_loihi.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/discovery_server.err.log
stdout_logfile=/var/log/discovery_server.out.log
environment=PORT="8001"
