export const TARGET_DATABASE = {
  sert_inhibition: {
    label: 'SERT (Serotonin Transporter)',
    shortLabel: 'SERT',
    category: 'Reuptake Inhibitors',
    description: 'Blocks serotonin reuptake → ↑ 5HT',
    neurotransmitter: 'Serotonin',
  },
  dat_inhibition: {
    label: 'DAT (Dopamine Transporter)',
    shortLabel: 'DAT',
    category: 'Reuptake Inhibitors',
    description: 'Blocks dopamine reuptake → ↑ DA',
    neurotransmitter: 'Dopamine',
  },
  net_inhibition: {
    label: 'NET (Norepinephrine Transporter)',
    shortLabel: 'NET',
    category: 'Reuptake Inhibitors',
    description: 'Blocks norepinephrine reuptake → ↑ NE',
    neurotransmitter: 'Norepinephrine',
  },
  gat_inhibition: {
    label: 'GAT (GABA Transporter)',
    shortLabel: 'GAT',
    category: 'Reuptake Inhibitors',
    description: 'Blocks GABA reuptake → ↑ GABA',
    neurotransmitter: 'GABA',
  },
  mao_a_inhibition: {
    label: 'MAO-A Inhibitor',
    shortLabel: 'MAO-A',
    category: 'Enzyme Inhibitors',
    description: 'Blocks MAO-A enzyme → ↑ 5HT, NE, DA',
    neurotransmitter: 'Multi (5HT/NE/DA)',
  },
  mao_b_inhibition: {
    label: 'MAO-B Inhibitor',
    shortLabel: 'MAO-B',
    category: 'Enzyme Inhibitors',
    description: 'Blocks MAO-B enzyme → ↑ DA',
    neurotransmitter: 'Dopamine',
  },
  ache_inhibition: {
    label: 'AChE Inhibitor',
    shortLabel: 'AChE',
    category: 'Enzyme Inhibitors',
    description: 'Blocks acetylcholinesterase → ↑ ACh',
    neurotransmitter: 'Acetylcholine',
  },
  gaba_transaminase_inhibition: {
    label: 'GABA-T Inhibitor',
    shortLabel: 'GABA-T',
    category: 'Enzyme Inhibitors',
    description: 'Blocks GABA transaminase → ↑ GABA',
    neurotransmitter: 'GABA',
  },
  da_precursor: {
    label: 'Dopamine Precursor (L-DOPA)',
    shortLabel: 'L-DOPA',
    category: 'Precursors',
    description: 'Increases DA synthesis',
    neurotransmitter: 'Dopamine',
  },
  d2_agonism: {
    label: 'D2 Receptor Agonist',
    shortLabel: 'D2 Agonist',
    category: 'Receptor Agonists',
    description: 'Activates D2 receptors',
    neurotransmitter: 'Dopamine',
  },
  d3_agonism: {
    label: 'D3 Receptor Agonist',
    shortLabel: 'D3 Agonist',
    category: 'Receptor Agonists',
    description: 'Activates D3 receptors',
    neurotransmitter: 'Dopamine',
  },
  d2_antagonism: {
    label: 'D2 Receptor Antagonist',
    shortLabel: 'D2 Antagonist',
    category: 'Receptor Antagonists',
    description: 'Blocks D2 receptors (antipsychotic)',
    neurotransmitter: 'Dopamine',
  },
  d3_antagonism: {
    label: 'D3 Receptor Antagonist',
    shortLabel: 'D3 Antagonist',
    category: 'Receptor Antagonists',
    description: 'Blocks D3 receptors',
    neurotransmitter: 'Dopamine',
  },
  d2_partial_agonism: {
    label: 'D2 Partial Agonist',
    shortLabel: 'D2 Partial',
    category: 'Partial Agonists',
    description: 'Stabilizes DA activity (Aripiprazole)',
    neurotransmitter: 'Dopamine',
  },
  ht1a_agonism: {
    label: '5-HT1A Agonist',
    shortLabel: '5-HT1A Agonist',
    category: 'Receptor Agonists',
    description: 'Activates 5-HT1A receptors',
    neurotransmitter: 'Serotonin',
  },
  ht2a_antagonism: {
    label: '5-HT2A Antagonist',
    shortLabel: '5-HT2A Antagonist',
    category: 'Receptor Antagonists',
    description: 'Blocks 5-HT2A receptors (atypical antipsychotics)',
    neurotransmitter: 'Serotonin',
  },
  alpha2_antagonism: {
    label: 'α2-Adrenergic Antagonist',
    shortLabel: 'α2 Antagonist',
    category: 'Receptor Antagonists',
    description: 'Blocks α2 autoreceptors → ↑ NE release',
    neurotransmitter: 'Norepinephrine',
  },
  h1_antagonism: {
    label: 'H1 Receptor Antagonist',
    shortLabel: 'H1 Antagonist',
    category: 'Receptor Antagonists',
    description: 'Blocks histamine (sedation)',
    neurotransmitter: 'Histamine',
  },
  gaba_a_pam: {
    label: 'GABA-A Positive Modulator',
    shortLabel: 'GABA-A PAM',
    category: 'GABA Modulators',
    description: 'Enhances GABA-A (benzodiazepines)',
    neurotransmitter: 'GABA',
  },
  nmda_antagonism: {
    label: 'NMDA Receptor Antagonist',
    shortLabel: 'NMDA Antagonist',
    category: 'Glutamate Modulators',
    description: 'Blocks NMDA receptors (memantine)',
    neurotransmitter: 'Glutamate',
  },
  glutamate_release_inhibition: {
    label: 'Glutamate Release Inhibitor',
    shortLabel: 'Glutamate Inhibitor',
    category: 'Glutamate Modulators',
    description: 'Reduces glutamate release',
    neurotransmitter: 'Glutamate',
  },
  voltage_gated_sodium_blocker: {
    label: 'Na+ Channel Blocker',
    shortLabel: 'Na+ Blocker',
    category: 'Ion Channels',
    description: 'Blocks voltage-gated Na+ channels',
    neurotransmitter: 'Multi',
  },
  alpha2delta_calcium_channel_blocker: {
    label: 'Ca2+ Channel Blocker (α2δ)',
    shortLabel: 'Ca2+ Blocker',
    category: 'Ion Channels',
    description: 'Blocks α2δ calcium channels (gabapentin)',
    neurotransmitter: 'Multi',
  },
};

export const TARGET_CATEGORIES = {
  'Reuptake Inhibitors': ['sert_inhibition', 'dat_inhibition', 'net_inhibition', 'gat_inhibition'],
  'Enzyme Inhibitors': [
    'mao_a_inhibition',
    'mao_b_inhibition',
    'ache_inhibition',
    'gaba_transaminase_inhibition',
  ],
  'Receptor Agonists': ['d2_agonism', 'd3_agonism', 'ht1a_agonism'],
  'Receptor Antagonists': [
    'd2_antagonism',
    'd3_antagonism',
    'ht2a_antagonism',
    'alpha2_antagonism',
    'h1_antagonism',
  ],
  'Partial Agonists': ['d2_partial_agonism'],
  Precursors: ['da_precursor'],
  'GABA Modulators': ['gaba_a_pam'],
  'Glutamate Modulators': ['nmda_antagonism', 'glutamate_release_inhibition'],
  'Ion Channels': ['voltage_gated_sodium_blocker', 'alpha2delta_calcium_channel_blocker'],
};

export const DEFAULT_TARGET_KEY = 'sert_inhibition';

export const targetShortLabel = (key) => TARGET_DATABASE[key]?.shortLabel || key;

export const targetNeurotransmitter = (key) => TARGET_DATABASE[key]?.neurotransmitter || 'Unknown';
